controller_manager:
  ros__parameters:
    update_rate: 10 #hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - hip_abduction_right
      - hip_abduction_left
      - hip_rotation_left
      - hip_rotation_right
      - toe_joint_left
      - toe_joint_right
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
